[workspace]
authors = ["Beni Dayan <dayanbeni@gmail.com>"]
channels = ["conda-forge"]
name = "Hello_World"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python Hellow_World.py"

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
cowpy = "==1.1.5"
